# Generated by Django 2.1.2 on 2019-01-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20190105_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
