# Generated by Django 2.1.2 on 2019-03-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20190303_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='last_update',
        ),
    ]
