# Generated by Django 2.1.2 on 2019-01-06 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='last_update',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
