# Generated by Django 2.1.2 on 2019-01-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20190105_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='family_quantity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, help_text='Total de pessoas que irão junto incluindo você', verbose_name='Número de pessoas'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='num_of_babies',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, help_text='Número de crianças até 5 anos'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='num_of_children',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, help_text='Número de crianças entre 6 e 12 anos'),
        ),
    ]
