# Generated by Django 2.1.2 on 2019-03-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='family_quantity',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, help_text='Total de pessoas que irão junto incluindo você', verbose_name='Número de pessoas'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='num_of_babies',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, help_text='Número de crianças até 5 anos', verbose_name='Número de bebes'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='num_of_children',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, help_text='Número de crianças entre 6 e 10 anos', verbose_name='Número de crianças'),
        ),
    ]
