# Generated by Django 2.1.2 on 2019-03-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='password',
            field=models.CharField(default='a4b20c43', max_length=9),
        ),
    ]
