# Generated by Django 2.1.2 on 2019-03-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20190306_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
