# Generated by Django 2.1.2 on 2019-03-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20190310_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='password',
            field=models.CharField(default='64c6ca47', max_length=9),
        ),
    ]
