# Generated by Django 2.1.2 on 2019-03-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20190310_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='message',
            field=models.TextField(blank=True, help_text='Deixe aqui sua mensagem aos noivos', null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='password',
            field=models.CharField(default='dedad77f', max_length=9),
        ),
    ]
