# Generated by Django 2.1.2 on 2019-03-03 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20190303_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular guest', primary_key=True, serialize=False),
        ),
    ]
