# Generated by Django 2.1.2 on 2019-03-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20190310_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='password',
            field=models.CharField(default='2297d6c2', max_length=9),
        ),
    ]
